services:
  - type: web
    name: trading-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_SECRET_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: LOGIN_USERNAME
        value: admin
      - key: LOGIN_PASSWORD
        sync: false
